### ISSUE TITLE
Skelet

### ISSUE THREAD

**Issue by yangwao** [FryTheDefi/dashboard#1]
- [x] Torus for getting user data - https://github.com/ethberlinzwei/Bounties/issues/35
- [ ] 3box social profile - https://github.com/ethberlinzwei/Bounties/issues/5
   - https://docs.3box.io/build/web-apps/public-data/profiles
- [x] 3box stroage space - https://github.com/ethberlinzwei/Bounties/issues/3
   - for user preferences
- [ ] 3box messaging 
	- ephmeral chat - https://github.com/3box/3box-js 
- [ ] Chainlink for price feeds - USD, DAI, BTC  https://github.com/ethberlinzwei/Bounties/issues/33
- [x] The Graph - https://github.com/ethberlinzwei/Bounties/issues/11
- [x] Kyber widget - https://developer.kyber.network/docs/Integrations-KyberWidgetGuide/ - one stop token swap

**Comment by yangwao** [comment]
whatever 🍟
